### ISSUE TITLE
Only traffic from browser is captured?

### ISSUE THREAD

**Issue by xyxzfj** [misakuo/Dream-Catcher#2]
Only traffic from browser (mobile chrome) is captured?
Traffic from my mobile app is not seen to be captured. Why?

**Comment by misakuo** [comment]
Some possible causes:
- Some of the traffic is not exchanged through http but through websocket or socket
- If the certificate is not installed, the https traffic is can not be captured
- Certificate verification on SSL handshake caused the MITM invalid
……

Capture based on VPN service maybe a good solution, but it is very hard to analysis of http(s) traffic on a huge of layer2 packet

**Comment by misakuo** [comment]
Has been a long time no reply, I will close the issue.
