### ISSUE TITLE
have set all configuration but still not success.

### ISSUE THREAD

**Issue by SwiftyWang** [misakuo/Dream-Catcher#3]
'Click to enable the HTTP proxy (It's maybe need waiting a bit time)' what is this mean?
 I have set all configurations, but still can not start capture. 
It is always loading...

**Comment by misakuo** [comment]
What version have you installed? and is there any information in the `chrome://inspect`?

**Comment by SwiftyWang** [comment]
v1.1.0, I can see this app in the chrome://inspect but the app always shows loading not connect success.

**Comment by misakuo** [comment]
Can you provide your device name and system version?

**Comment by SwiftyWang** [comment]
sharp android6.0. BTW where to enable http proxy u said in the step 2?

**Comment by misakuo** [comment]
In my device:
Settings -> WLAN -> **LONG PRESS THE ACTIVE CONNECTION** -> Modify Network -> 

And trying to turn off then turn on WLAN

**Comment by misakuo** [comment]
Has been a long time no reply, I will close the issue
