### ISSUE TITLE
a better way to use Dream-Catcher

### ISSUE THREAD

**Issue by connonfodder** [misakuo/Dream-Catcher#4]
Hi,  after failed to use Dream-Catcher, I come to Flidder. I can use that to capture something, but I really want to use this, I got some problem when I use Flidder, I wish it's helpful for someone want to use this.

first, support a certification file to download then we can install it manually. because I got a crash in the step. (install type is vpn/app.)
second, make something clearly. such as after setup, turn off wifi and turn wifi, start app then going to Chrom. I think it will avoid something wrong.

**Comment by misakuo** [comment]
Thanks for you report.
The CA file is built in APP now but it is not automatically installed.
For the second question, welcome to participate in document construction.
Thanks again.
